In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical


In [2]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 20s 2us/step


In [8]:
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

In [10]:
x_train.shape

(60000, 28, 28)

In [7]:
time_steps, features = x_train.shape[1], x_train.shape[2]
x_train = x_train.reshape(x_train.shape[0], time_steps, features)
x_test = x_test.reshape(x_test.shape[0], time_steps, features)

In [3]:
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
sequence_length = 3  # Define the sequence length (how many time steps to consider)

# Create sequences
sequences = []
target = []
for i in range(len(data) - sequence_length):
    sequences.append(data[i:i + sequence_length])
    target.append(data[i + sequence_length])

In [4]:
sequences

[array([10, 20, 30]),
 array([20, 30, 40]),
 array([30, 40, 50]),
 array([40, 50, 60]),
 array([50, 60, 70]),
 array([60, 70, 80]),
 array([70, 80, 90])]

In [5]:
target

[np.int64(40),
 np.int64(50),
 np.int64(60),
 np.int64(70),
 np.int64(80),
 np.int64(90),
 np.int64(100)]

In [ ]:
x = [[[-0.04588735,  0.04821293,  0.02707684 , 0.03532112],
  [-0.01999545, -0.04968796, -0.02757902 , 0.00817414],
  [ 0.02031758, -0.01175624,  0.01233627,  0.01491675],
  [-0.01573961, -0.03532983, -0.02621815 ,-0.04042824],
  [ 0.02531271, -0.01728104 ,-0.00472096, -0.04027735],
  [-0.04076502, -0.04600718, -0.03657167, -0.04884919],
  [-0.00248233, -0.04897319, -0.01218885,  0.02799994],
  [-0.00248233 ,-0.04897319, -0.01218885 , 0.02799994]],

 [[-0.04588735,  0.04821293,  0.02707684, , 0.03532112],
  [-0.02176586 ,-0.03552277,  0.0177248,  -0.01874503],
  [ 0.04428699 , 0.03702401, -0.038103 ,   0.01531515],
  [ 0.01737973 ,-0.01626869, -0.03483053 , 0.00736971],
  [-0.02679001 ,-0.00531564,  0.02538358 ,-0.00660758],
  [-0.00248233, -0.04897319 ,-0.01218885,  0.02799994],
  [-0.00248233 ,-0.04897319 ,-0.01218885,  0.02799994],
  [-0.00248233, -0.04897319, -0.01218885,  0.02799994]],

 [[-0.04588735,  0.04821293,  0.02707684,  0.03532112],
  [-0.01086154 ,-0.00346394,  0.01886177 ,-0.02077385],
  [-0.04637978,  0.01801422,  0.00417098 ,-0.0366376 ],
  [ 0.03626612, -0.03860765,  0.00117645, -0.00586362],
  [-0.02679001 ,-0.00531564,  0.02538358, -0.00660758],
  [ 0.00779638, -0.04695494 ,-0.02802014 ,-0.01979377],
  [-0.03570173,  0.04125914 ,-0.04764031 ,-0.03406505],
  [ 0.00056888 , 0.01333905 ,-0.04374031 , 0.03733016]]]